### PR TITLE
Add threshold to automatically delete oldest file in temp directory

### PR DESCRIPTION
**Pull request by bjcscat**
This probably break win32 compatibility if they don't have the sysinternals 'du' utility

### CODE REVIEW

**Comment by TheEssem** [comment]
Seems a bit insecure, I'm sure this could be done using the fs module instead of shelling out to du.

**Comment by bjcscat** [comment]
It can. It would just have to be done recursively so hence why I went with du.

**Comment by samhza** [comment]
It can be done recursively without `du`. Shelling out to `du` is not portable.

**Comment by bjcscat** [comment]
I reworked it to be recursive with a some caching

**Comment by TheEssem** [comment]
Looks good, sorry for the late merge.

**Pull request merged**
