### PR TITLE
disallow user 927240253272645662 from using esmbot

### PR DESCRIPTION
**Pull request by CoolElectronics**
essem please

### CODE REVIEW

**Comment by thonkinator** [comment]
this is quite possibly the best addition to any codebase in history

**Comment by TheEssem** [comment]
https://wetdry.world/@esm/111434965993296651

**Review by Nightcaat — COMMENTED** [review]
I have to say this pull request will definitely disallow the Discord user with the ID 927240253272645662 from using esmBot. Concerning

**Comment by thonkinator** [comment]
noooo how could you close 😔

**Pull request closed without merging**
